import Head from "next/head";
// import Image from "next/image";
import { Footer } from "../components/layout/footer";
import { Header } from "../components/layout/header";
import { Blog } from "../components/layout/top/blog/blog";
import { Github } from "../components/layout/top/github/github";
import { MainVisual } from "../components/layout/top/mv";
import { Portfolio } from "../components/layout/top/portfolio/portfolio";
import { Section } from "../components/layout/top/section";
import { Twitter } from "../components/layout/top/twitter/twitter";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <MainVisual />
        <Section title="Blog" content={<Blog />} />
        <Section title="Portfolio" content={<Portfolio />} />
        <Section title="Github" content={<Github />} />
        <Section title="Twitter" content={<Twitter />} />
      </main>

      <Footer />
    </div>
  );
}
